name: Auto Commit Quotes
on:
  schedule:
      - cron: '*/1 * * * *'
    workflow_dispatch:

jobs:
  commit-quotes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Commit quotes every 4.5 milliseconds
        run: |
          while true; do
            timestamp=$(date +%s%3N)
            mkdir -p quotes
            echo "Technology is best when it brings people together. - Matt Mullenweg" >> "quotes/quote_$timestamp.txt"
            git add .
            git commit -m "Add quote at $(date --utc +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin main
            sleep 0.0045
          done
